spring:
  application:
    name: poc-rsocket-jwt
  rsocket:
    server:
      port: 7000
      transport: websocket

logging.level.io.rsocket.FrameLogger: DEBUG

poc.rsocket.jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApF0EWpMp1awm6t/F+uKSbtlZbMA24b0u
    Y0ztPRotO1MCmhFSEGde9nTN+Y6RxqHfk/CcDsTnFYTYa0wwdqe2k0bElsIAN1AQPH46kdpeL/+p
    7cvQatabhnEwKqd6aV3FkBsHOCbvUJT2zrw5CFUOvCrubkIHMaV68s7N6s80rGh5TN6oFq0qXqjs
    kuD2dZMZ2/fCBHNOv9O6S6pyjMDRvSCA39DZQaTnD9XC9V+BaXi7YwpEKesAmdCqSSdyyk4rrErf
    YFNA+vR0IX0PlktfOBoYaVm7OCI0QWekhD5FZ/ZTK8QAfj5TQmaL6p6zrB32DMx9mXZhwvwMtE6Y
    PhetzwIDAQAB
    -----END PUBLIC KEY-----
